name: 'Trigger CircleCI Pipeline'
description: 'Manually trigger a pipeline in CircleCI'
inputs:
  triggered-workflow:
    description: 'Name of the workflow to trigger'
    required: true
    default: 'default'
  circleci-token:
    description: 'A personal API token to CircleCI'
    required: true
  wait-for-completion:
    description: 'Whether to wait for the workflow to finish'
    required: false
    default: 'false'
  kwargs:
    description: 'json of extra arguments to pass to the workflow'
    required: false
    default: '{}'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/trigger_circleci_pipeline.sh
      shell: bash
      env:
          CIRCLECI_USER_PERSONAL_API_TOKEN: ${{ inputs.circleci-token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          BRANCH_REF: ${{ github.head_ref || github.ref }}
          WORKFLOW_KWARGS: ${{ inputs.kwargs }}
          TRIGGERED_WORKFLOW: ${{ inputs.triggered-workflow }}
          SHOULD_WAIT: ${{ inputs.wait-for-completion }}
