name: 'Trigger CircleCI Pipeline'
description: 'Manually trigger a pipeline in CircleCI'
inputs:
  triggered-workflow:
    description: 'Name of the workflow to trigger'
    required: true
    default: 'default'
  circleci-token:
    description: 'A personal API token to CircleCI'
    required: true
  triggered_key:
    description: 'A uuid specific for this job added by user'
    default: '0000-0000-0000-000000000'
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/trigger_circleci_pipeline.sh ${{ inputs.triggered-workflow }} ${{ inputs.triggered_key }}
      shell: bash
      env:
          CIRCLECI_USER_PERSONAL_API_TOKEN: ${{ inputs.circleci-token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          BRANCH_REF: ${{ github.head_ref || github.ref }}
